export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  REFUNDED: "REFUNDED",
  CHARGEBACK: "CHARGEBACK",
  CHALLENGE: "CHALLENGE",
  AUTHORIZED: "AUTHORIZED",
} as const;

export type PaymentStatus = typeof PAYMENT_STATUS[keyof typeof PAYMENT_STATUS];

export const PAYMENT_CONFIG = {
  EXPIRED_HOURS: 24,
  MAX_RETRIES: 2,
};
