version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: portal_sekolah_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: portal_sekolah
    ports:
      - '5432:5432'
    volumes:
      - portal_sekolah_pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: portal_sekolah_redis
    ports:
      - '6379:6379'
    volumes:
      - portal_sekolah_redisdata:/data
    restart: always

volumes:
  portal_sekolah_pgdata:
  portal_sekolah_redisdata:
